---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangyuan.
--- DateTime: 2023/5/28 17:19
---
if redis.call('get',KEYS[1]) == ARGV[1] then
    return redis.call('EXPIRE',KEYS[1],ARGV[2])
else
    return 0
end